# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := gensokyo-upside-down.out

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

gensokyo-upside-down.out: 
	@echo "==== Building gensokyo-upside-down.out ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f gensokyo-upside-down.out.make

clean:
	@${MAKE} --no-print-directory -C . -f gensokyo-upside-down.out.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   gensokyo-upside-down.out"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
